name: Buildbinary

on:
  push:
    branches: [ main ]

jobs:

  buildMacRelease:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
        repository: 'DecentralizeJustice/HWI'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.12'
        architecture: 'x64'
    - name: setup pyenv
      uses: "gabrielfalcao/pyenv-action@v5"
    - run: env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.8
    - run: brew install libusb
    - run: ./contrib/build_bin.sh
