
name: DebugMac

on:
  push:
    branches: [ debugMac ]

jobs:

  buildMacRelease:
    runs-on: macos-10.14
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-node@main
      with:
        # fix till https://github.com/actions/setup-node/issues/121 is solved
        node-version: 12.16.1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: node -p "require('./package').version" > get_Version.txt
    - uses: pCYSl5EDgo/cat@master
      id: getVersion
      with:
        path: get_Version.txt
        trim: true

    - run: yarn install
    - run: yarn run test
    - run: yarn run build
      env:
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}

    - name: Upload latest-mac.yml
      uses: actions/upload-artifact@v2
      with:
        name: latest-mac.yml
        path: dist_electron/latest-mac.yml

    - name: Upload mac.zip
      uses: actions/upload-artifact@v2
      with:
        name: GuidingWallet.zip
        path: dist_electron/GuidingWallet.zip

    - name: Upload mac dmg
      uses: actions/upload-artifact@v2
      with:
        name: GuidingWallet.dmg
        path: dist_electron/GuidingWallet.dmg

    - name: Upload dmg.blockmap
      uses: actions/upload-artifact@v2
      with:
        name: GuidingWallet.dmg.blockmap
        path: dist_electron/GuidingWallet.dmg.blockmap
