
name: BuildRelease

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  #   types: [closed]

jobs:


  buildWindowsRelease:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-node@master
      with:
        #
        # fix till https://github.com/actions/setup-node/issues/121 is solved
        node-version: 12.16.1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: yarn install
    - run: yarn run build
      # env:
      #     CSC_KEY_PASSWORD: ${{ secrets.Windows_CERTS_PASSWORD }}
      #     CSC_LINK: ${{ secrets.Windows_CERTS }}

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v2
      with:
        name: GuidingWallet.exe
        path: ./dist_electron/GuidingWallet Setup 0.1.0.exe


  buildMacRelease:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - uses: actions/setup-node@master
      with:
        #
        # fix till https://github.com/actions/setup-node/issues/121 is solved
        node-version: 12.16.1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: yarn install
    - run: yarn run build
      env:
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
    - name: Upload Mac Installer
      uses: actions/upload-artifact@v2
      with:
        name: GuidingWallet.dmg
        path: ./dist_electron/GuidingWallet-0.1.0.dmg


  createRelease:
    runs-on: ubuntu-latest
    needs: [buildWindowsRelease, buildMacRelease]
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{github.sha}}
        release_name: Demo Build v0.1.0
        body: |
          Add Release Notes
          Built From Master Commit ${{github.sha}}
        draft: true
        prerelease: true

    - name: Download Windows Installer
      uses: actions/download-artifact@v2
      with:
        name: GuidingWallet.exe

    - name: Download Mac Installer
      uses: actions/download-artifact@v2
      with:
        name: GuidingWallet.dmg

    - name: Upload Mac Release Asset
      id: upload-release-asset-mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: GuidingWallet-0.1.0.dmg
        asset_name: Mac-GuidingWallet.dmg
        asset_content_type: application/octet-stream

    - name: Upload Release Windows Asset
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: GuidingWallet Setup 0.1.0.exe
        asset_name: Windows-GuidingWallet.exe
        asset_content_type: application/octet-stream
