
name: BuildMasterRelease

on:
  push:
    branches: [ master ]

jobs:
  buildRelease:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        # fix till https://github.com/actions/setup-node/issues/121 is solved
        node-version: 12.16.1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: yarn install
    - run: yarn run build
    - run: ls
